name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake test
